import type { Course, CourseUnit, KnowledgeNode, University, UniversityMajor, ApplicationGuide } from '@/types';

export const seedCourses: Course[] = [
  { id: 'ap-calc-bc', curriculum: 'AP', subject_code: 'CALC_BC', subject_name: 'Calculus BC', full_name: 'AP Calculus BC', description: 'AP Calculus BC is an introductory college-level calculus course that covers differential and integral calculus, plus series.', total_units: 10, estimated_hours: 150, official_guide_url: 'https://apstudents.collegeboard.org/courses/ap-calculus-bc', is_active: true },
  { id: 'ap-physics-c', curriculum: 'AP', subject_code: 'PHYSICS_C', subject_name: 'Physics C', full_name: 'AP Physics C (Mechanics + E&M)', description: 'AP Physics C is a calculus-based physics course covering mechanics and electricity & magnetism.', total_units: 14, estimated_hours: 180, official_guide_url: 'https://apstudents.collegeboard.org/courses/ap-physics-c-mechanics', is_active: false },
  { id: 'ib-math-aa-hl', curriculum: 'IB', subject_code: 'MATH_AA_HL', subject_name: 'Math AA HL', full_name: 'IB Mathematics: Analysis and Approaches HL', description: 'Rigorous mathematics course focusing on analytical methods, calculus, and algebraic structures.', total_units: 5, estimated_hours: 240, official_guide_url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/mathematics/', is_active: false },
  { id: 'ib-physics-hl', curriculum: 'IB', subject_code: 'PHYSICS_HL', subject_name: 'Physics HL', full_name: 'IB Physics HL', description: 'Comprehensive physics course covering mechanics, thermodynamics, waves, electricity, and modern physics.', total_units: 12, estimated_hours: 240, official_guide_url: 'https://www.ibo.org/programmes/diploma-programme/curriculum/sciences/', is_active: false },
];

export const seedUnits: Record<string, CourseUnit[]> = {
  'ap-calc-bc': [
    { id: 'u1', course_id: 'ap-calc-bc', unit_number: 1, unit_title: 'Limits and Continuity', description: 'Understanding limits graphically, numerically, and analytically. Continuity and types of discontinuities.', estimated_hours: 15 },
    { id: 'u2', course_id: 'ap-calc-bc', unit_number: 2, unit_title: 'Differentiation: Definition and Fundamental Properties', description: 'Defining the derivative, basic differentiation rules, product and quotient rules.', estimated_hours: 18 },
    { id: 'u3', course_id: 'ap-calc-bc', unit_number: 3, unit_title: 'Differentiation: Composite, Implicit, and Inverse Functions', description: 'Chain rule, implicit differentiation, derivatives of inverse functions.', estimated_hours: 15 },
    { id: 'u4', course_id: 'ap-calc-bc', unit_number: 4, unit_title: 'Contextual Applications of Differentiation', description: 'Related rates, straight-line motion, L\'Hospital\'s rule.', estimated_hours: 12 },
    { id: 'u5', course_id: 'ap-calc-bc', unit_number: 5, unit_title: 'Analytical Applications of Differentiation', description: 'Mean Value Theorem, extrema, concavity, optimization, graphical analysis.', estimated_hours: 15 },
    { id: 'u6', course_id: 'ap-calc-bc', unit_number: 6, unit_title: 'Integration and Accumulation of Change', description: 'Definite integrals, Fundamental Theorem of Calculus, accumulation functions.', estimated_hours: 20 },
    { id: 'u7', course_id: 'ap-calc-bc', unit_number: 7, unit_title: 'Differential Equations', description: 'Modeling with differential equations, separation of variables, slope fields.', estimated_hours: 12 },
    { id: 'u8', course_id: 'ap-calc-bc', unit_number: 8, unit_title: 'Applications of Integration', description: 'Average value, area between curves, volume with cross sections, arc length.', estimated_hours: 15 },
    { id: 'u9', course_id: 'ap-calc-bc', unit_number: 9, unit_title: 'Parametric Equations, Polar Coordinates, and Vector-Valued Functions', description: 'BC Only. Parametric differentiation, polar curves, vector-valued functions.', estimated_hours: 15 },
    { id: 'u10', course_id: 'ap-calc-bc', unit_number: 10, unit_title: 'Infinite Sequences and Series', description: 'BC Only. Convergence tests, power series, Taylor and Maclaurin series.', estimated_hours: 18 },
  ],
};

export const seedNodes: Record<string, KnowledgeNode[]> = {
  'u1': [
    { id: 'n1-1', course_id: 'ap-calc-bc', unit_id: 'u1', level: 1, node_number: '1.1', title: 'Introducing Calculus: Can Change Occur at an Instant?', content: 'Calculus is the mathematics of change. While algebra deals with constant rates, calculus allows us to analyze instantaneous rates of change. The central question: how do we measure change at a single instant?', content_summary: 'Introduction to calculus as the study of instantaneous change.', key_concepts: ['instantaneous rate of change', 'average rate of change', 'secant line', 'tangent line'], key_formulas: [{ formula: '\\text{Average Rate of Change} = \\frac{f(b) - f(a)}{b - a}', description: 'The slope of the secant line between two points' }], common_mistakes: [{ mistake: 'Confusing average rate with instantaneous rate', correction: 'Average rate requires an interval; instantaneous rate is the limit as the interval shrinks to zero.' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 18', prerequisites: [], related_nodes: ['n1-2'], linked_exercises: [], difficulty: 1, estimated_minutes: 15 },
    { id: 'n1-2', course_id: 'ap-calc-bc', unit_id: 'u1', level: 1, node_number: '1.2', title: 'Defining Limits and Using Limit Notation', content: 'The limit of f(x) as x approaches c is L if we can make f(x) arbitrarily close to L by taking x sufficiently close to c. Notation: lim(x→c) f(x) = L. Limits describe the behavior of a function near a point, not necessarily at the point.', content_summary: 'Formal definition of limits and limit notation.', key_concepts: ['limit notation', 'two-sided limit', 'one-sided limits', 'limit exists'], key_formulas: [{ formula: '\\lim_{x \\to c} f(x) = L', description: 'The limit of f(x) as x approaches c equals L' }, { formula: '\\lim_{x \\to c^-} f(x) \\text{ and } \\lim_{x \\to c^+} f(x)', description: 'Left-hand and right-hand limits' }], common_mistakes: [{ mistake: 'Thinking the limit must equal f(c)', correction: 'The limit depends on nearby values, not f(c) itself. The function may be undefined at c.' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 19', prerequisites: ['n1-1'], related_nodes: ['n1-3', 'n1-4'], linked_exercises: [], difficulty: 2, estimated_minutes: 20 },
    { id: 'n1-3', course_id: 'ap-calc-bc', unit_id: 'u1', level: 1, node_number: '1.3', title: 'Estimating Limit Values from Graphs', content: 'To estimate a limit from a graph, observe the y-value the function approaches as x approaches c from both sides. If the left and right approaches agree, the two-sided limit exists and equals that value.', content_summary: 'Estimating limits by analyzing function graphs.', key_concepts: ['graphical estimation', 'left approach', 'right approach'], key_formulas: [], common_mistakes: [{ mistake: 'Looking at f(c) instead of the approaching value', correction: 'Focus on where the curve is heading, not the point itself (which may be a hole).' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 20', prerequisites: ['n1-2'], related_nodes: ['n1-4'], linked_exercises: [], difficulty: 1, estimated_minutes: 15 },
    { id: 'n1-4', course_id: 'ap-calc-bc', unit_id: 'u1', level: 1, node_number: '1.4', title: 'Estimating Limit Values from Tables', content: 'Construct a table of values for f(x) as x approaches c from both sides. If the function values approach the same number L from both directions, then lim(x→c) f(x) = L.', content_summary: 'Using numerical tables to estimate limits.', key_concepts: ['numerical estimation', 'table of values'], key_formulas: [], common_mistakes: [{ mistake: 'Using too few values or too far from c', correction: 'Choose x-values very close to c (e.g., c ± 0.1, c ± 0.01, c ± 0.001).' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 21', prerequisites: ['n1-2'], related_nodes: ['n1-3'], linked_exercises: [], difficulty: 1, estimated_minutes: 15 },
    { id: 'n1-5', course_id: 'ap-calc-bc', unit_id: 'u1', level: 1, node_number: '1.5', title: 'Determining Limits Using Algebraic Properties', content: 'Limit properties: sum, difference, product, quotient, and power rules. If lim(x→c) f(x) = L and lim(x→c) g(x) = M, then lim(x→c)[f(x) ± g(x)] = L ± M, lim(x→c)[f(x)g(x)] = LM, and lim(x→c)[f(x)/g(x)] = L/M (M≠0).', content_summary: 'Using algebraic properties to compute limits.', key_concepts: ['limit laws', 'sum rule', 'product rule', 'quotient rule', 'power rule'], key_formulas: [{ formula: '\\lim_{x \\to c}[f(x) \\pm g(x)] = \\lim_{x \\to c}f(x) \\pm \\lim_{x \\to c}g(x)', description: 'Sum/Difference rule' }, { formula: '\\lim_{x \\to c}[f(x) \\cdot g(x)] = \\lim_{x \\to c}f(x) \\cdot \\lim_{x \\to c}g(x)', description: 'Product rule' }], common_mistakes: [{ mistake: 'Applying the quotient rule when the denominator limit is 0', correction: 'If the denominator limit is 0, the quotient rule does not apply. You need algebraic manipulation or other techniques.' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 22', prerequisites: ['n1-2'], related_nodes: ['n1-6'], linked_exercises: [], difficulty: 2, estimated_minutes: 20 },
    { id: 'n1-6', course_id: 'ap-calc-bc', unit_id: 'u1', level: 1, node_number: '1.6', title: 'Determining Limits Using Algebraic Manipulation', content: 'When direct substitution yields indeterminate forms (0/0), use factoring, rationalizing, or simplifying complex fractions to rewrite the expression before taking the limit.', content_summary: 'Algebraic techniques for resolving indeterminate limits.', key_concepts: ['factoring', 'rationalizing', 'conjugate', 'indeterminate form'], key_formulas: [], common_mistakes: [{ mistake: 'Giving up when direct substitution gives 0/0', correction: '0/0 is a signal to manipulate algebraically—factor, rationalize, or simplify.' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 23', prerequisites: ['n1-5'], related_nodes: [], linked_exercises: [], difficulty: 3, estimated_minutes: 25 },
  ],
  'u3': [
    { id: 'n3-1', course_id: 'ap-calc-bc', unit_id: 'u3', level: 1, node_number: '3.1', title: 'The Chain Rule', content: 'The Chain Rule is used to differentiate composite functions. If y = f(g(x)), then dy/dx = f\'(g(x)) · g\'(x). In Leibniz notation: if y = f(u) and u = g(x), then dy/dx = dy/du · du/dx.', content_summary: 'Differentiating composite functions using the Chain Rule.', key_concepts: ['composite function', 'chain rule', 'outer function', 'inner function'], key_formulas: [{ formula: '\\frac{d}{dx}[f(g(x))] = f\\\'(g(x)) \\cdot g\\\'(x)', description: 'Chain Rule' }, { formula: '\\frac{dy}{dx} = \\frac{dy}{du} \\cdot \\frac{du}{dx}', description: 'Leibniz notation form' }], common_mistakes: [{ mistake: 'Forgetting to multiply by the derivative of the inner function', correction: 'Always identify the outer and inner functions, differentiate each separately, then multiply.' }, { mistake: 'Stopping after differentiating the outer function only', correction: 'The chain rule requires BOTH f\'(g(x)) AND g\'(x).' }], source_document: 'AP Calculus Course Description 2024', source_page: 'p. 42', prerequisites: ['n2-2'], related_nodes: ['n3-2'], linked_exercises: [], difficulty: 3, estimated_minutes: 25 },
  ],
};

export const seedUniversities: University[] = [
  { id: 'mit', name: 'Massachusetts Institute of Technology', short_name: 'MIT', country: 'USA', region: 'Massachusetts', type: 'private', ranking_qs: 1, ranking_us_news: 2, website: 'https://web.mit.edu', description: 'MIT is a world-renowned private research university in Cambridge, Massachusetts. Known for its strength in engineering, physical sciences, and technology.', campus_info: 'Urban campus along the Charles River, 168 acres', tuition_range: '$59,750/year', acceptance_rate: 0.04, student_population: 11500, is_active: true },
  { id: 'stanford', name: 'Stanford University', short_name: 'Stanford', country: 'USA', region: 'California', type: 'private', ranking_qs: 3, ranking_us_news: 3, website: 'https://www.stanford.edu', description: 'Stanford University is a private research university in Stanford, California. Known for its entrepreneurial culture and proximity to Silicon Valley.', campus_info: 'Suburban campus, 8,180 acres', tuition_range: '$62,484/year', acceptance_rate: 0.037, student_population: 17000, is_active: true },
  { id: 'harvard', name: 'Harvard University', short_name: 'Harvard', country: 'USA', region: 'Massachusetts', type: 'private', ranking_qs: 4, ranking_us_news: 3, website: 'https://www.harvard.edu', description: 'Harvard is the oldest institution of higher learning in the United States, known for its law, business, and medical schools.', campus_info: 'Urban campus in Cambridge, 209 acres', tuition_range: '$59,076/year', acceptance_rate: 0.034, student_population: 23000, is_active: true },
  { id: 'cmu', name: 'Carnegie Mellon University', short_name: 'CMU', country: 'USA', region: 'Pennsylvania', type: 'private', ranking_qs: 51, ranking_us_news: 24, website: 'https://www.cmu.edu', description: 'Carnegie Mellon is a private research university in Pittsburgh, Pennsylvania. World-renowned for computer science, robotics, and fine arts.', campus_info: 'Urban campus, 140 acres', tuition_range: '$63,829/year', acceptance_rate: 0.11, student_population: 15000, is_active: true },
  { id: 'ucla', name: 'University of California, Los Angeles', short_name: 'UCLA', country: 'USA', region: 'California', type: 'public', ranking_qs: 29, ranking_us_news: 15, website: 'https://www.ucla.edu', description: 'UCLA is a public land-grant research university in Los Angeles. The most applied-to university in the United States.', campus_info: 'Urban campus, 419 acres', tuition_range: '$44,524/year (out-of-state)', acceptance_rate: 0.086, student_population: 46000, is_active: true },
  { id: 'cambridge', name: 'University of Cambridge', short_name: 'Cambridge', country: 'UK', region: 'Cambridgeshire', type: 'public', ranking_qs: 2, ranking_the: 5, website: 'https://www.cam.ac.uk', description: 'The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209, it is the second-oldest university in the English-speaking world.', campus_info: 'Collegiate university, scattered throughout the city', tuition_range: '£25,734-£39,162/year (intl)', acceptance_rate: 0.21, student_population: 21000, is_active: true },
  { id: 'oxford', name: 'University of Oxford', short_name: 'Oxford', country: 'UK', region: 'Oxfordshire', type: 'public', ranking_qs: 3, ranking_the: 1, website: 'https://www.ox.ac.uk', description: 'The University of Oxford is a collegiate research university in Oxford, England. The oldest university in the English-speaking world.', campus_info: 'Collegiate university, 39 colleges', tuition_range: '£28,950-£44,240/year (intl)', acceptance_rate: 0.17, student_population: 24000, is_active: true },
  { id: 'imperial', name: 'Imperial College London', short_name: 'Imperial', country: 'UK', region: 'London', type: 'public', ranking_qs: 6, ranking_the: 8, website: 'https://www.imperial.ac.uk', description: 'Imperial College London is a public research university in London. Focuses exclusively on science, engineering, medicine, and business.', campus_info: 'South Kensington campus, central London', tuition_range: '£37,900-£41,650/year', acceptance_rate: 0.14, student_population: 20000, is_active: true },
];

export const seedMajors: UniversityMajor[] = [
  { id: 'm1', university_id: 'mit', major_name: 'Computer Science', college: 'School of Engineering', description: 'The EECS department at MIT is the largest undergraduate program. Covers algorithms, AI, systems, and theory.', degree_type: 'BS/ MEng', duration_years: 4, requirements: 'Strong math background, programming experience recommended', career_paths: ['Software Engineer', 'AI Researcher', 'Quantitative Analyst'], is_active: true },
  { id: 'm2', university_id: 'cmu', major_name: 'Computer Science', college: 'School of Computer Science', description: 'CMU\'s School of Computer Science is consistently ranked #1 in the world. Known for robotics, machine learning, and human-computer interaction.', degree_type: 'BS', duration_years: 4, requirements: 'Strong math and science background', career_paths: ['Software Engineer', 'Research Scientist', 'Startup Founder'], is_active: true },
  { id: 'm3', university_id: 'stanford', major_name: 'Computer Science', college: 'School of Engineering', description: 'Stanford CS sits in the heart of Silicon Valley. Strong emphasis on entrepreneurship and interdisciplinary work.', degree_type: 'BS/MS', duration_years: 4, requirements: 'Excellent academic record, especially in math', career_paths: ['Tech Entrepreneur', 'Software Engineer', 'Product Manager'], is_active: true },
  { id: 'm4', university_id: 'cambridge', major_name: 'Natural Sciences', college: 'Various Colleges', description: 'Cambridge Natural Sciences is a broad-based physical and biological sciences program. Students specialize from Year 2.', degree_type: 'BA', duration_years: 3, requirements: 'IB 40-42 with HL sciences at 7,7,6 or A-Level A*A*A', career_paths: ['Research Scientist', 'Medical Doctor', 'Science Consultant'], is_active: true },
  { id: 'm5', university_id: 'ucla', major_name: 'Computer Science', college: 'Samueli School of Engineering', description: 'UCLA CS offers a strong theoretical foundation combined with practical software engineering skills.', degree_type: 'BS', duration_years: 4, requirements: 'Strong math background, competitive GPA', career_paths: ['Software Engineer', 'Data Scientist', 'Product Manager'], is_active: true },
];

export const seedApplicationGuides: ApplicationGuide[] = [
  { id: 'g1', country: 'USA', title: 'US Application Overview', content: 'US universities use a holistic admissions process. Most schools accept the Common Application or Coalition Application. Key components: transcripts, test scores (SAT/ACT, often optional), essays, recommendation letters, extracurricular activities list.', section: 'overview', order_index: 1, is_active: true },
  { id: 'g2', country: 'USA', title: 'Early Decision vs Early Action vs Regular Decision', content: '**Early Decision (ED)**: Binding agreement. If accepted, you must attend. Deadline: typically Nov 1. **Early Action (EA)**: Non-binding. Apply early, get decision early. Deadline: typically Nov 1. **Regular Decision (RD)**: Standard application round. Deadline: typically Jan 1-15.', section: 'timelines', order_index: 1, is_active: true },
  { id: 'g3', country: 'USA', title: 'Common Application Essay', content: 'The Common App requires one main essay (650 words max) from a choice of 7 prompts. This is your chance to show personality beyond grades. Tips: be authentic, tell a story, show growth. Supplemental essays vary by school (typically 150-400 words each).', section: 'essays', order_index: 1, is_active: true },
  { id: 'g4', country: 'USA', title: 'SAT / ACT Strategy', content: 'Most US schools are test-optional as of 2024. Submit scores if they are at or above the school\'s 50th percentile. SAT: 1600 scale. ACT: 36 scale. Plan to take 2-3 times. Register early for preferred dates.', section: 'testing', order_index: 1, is_active: true },
  { id: 'g5', country: 'UK', title: 'UK Application Overview', content: 'All UK university applications go through UCAS (Universities and Colleges Admissions Service). You can apply to up to 5 courses. Key components: Personal Statement (4000 characters), academic reference, predicted grades. Oxford and Cambridge have additional admissions tests and interviews.', section: 'overview', order_index: 1, is_active: true },
  { id: 'g6', country: 'UK', title: 'UCAS Personal Statement', content: 'One personal statement for all 5 choices. Focus: academic passion, relevant reading/experiences, career aspirations. Structure: 75% academic, 25% extracurricular. No mention of specific university names. Start drafting in Year 12 summer.', section: 'essays', order_index: 1, is_active: true },
  { id: 'g7', country: 'UK', title: 'Oxbridge Application Timeline', content: 'Oxford and Cambridge have earlier deadlines: UCAS deadline Oct 15 (vs Jan 31 for other UK schools). Additional steps: admissions test registration (by Sept 30), test date (late Oct/early Nov), interview invitations (Nov), interviews (Dec), decision (Jan).', section: 'timelines', order_index: 1, is_active: true },
  { id: 'g8', country: 'Canada', title: 'Canada Application Overview', content: 'Canadian applications are more straightforward than US. Most provinces use a centralized application system (e.g., OUAC for Ontario). Key components: transcripts, English proficiency test, sometimes supplemental applications for competitive programs. Less emphasis on extracurriculars and essays.', section: 'overview', order_index: 1, is_active: true },
];
